Error in Donut.gds:

Traceback (most recent call last):
  File "/tmp/tmpqdilaz8o/temp_script.py", line 12, in <module>
    outer_circle = gdspy.Round(
                   ^^^^^^^^^^^^
TypeError: Round.__init__() got an unexpected keyword argument 'num_points'
